In [1]:
from stable_baselines3.common.vec_env import VecVideoRecorder, DummyVecEnv
from stable_baselines3 import SAC, HerReplayBuffer
from environments import *

import torch
import numpy as np
import gym
import imageio

c:\Users\ssuro\anaconda3\envs\torch\lib\site-packages\torch\utils\tensorboard\__init__.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion


In [2]:
env_id = 'G1GoalDist-v1'
video_folder = 'renders'
video_length = 500

In [3]:
model = SAC.load("trained_models/g1-reptile/sac")

c:\Users\ssuro\anaconda3\envs\torch\lib\site-packages\stable_baselines3\common\buffers.py:228: UserWarning: This system does not have apparently enough memory to store the complete replay buffer 27.89GB > 15.22GB
  warnings.warn(


In [4]:
env = gym.make(env_id)

c:\Users\ssuro\anaconda3\envs\torch\lib\site-packages\gym\core.py:329: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
c:\Users\ssuro\anaconda3\envs\torch\lib\site-packages\gym\wrappers\step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [5]:
tasks = env.sample_tasks(36)

In [6]:
for task in tasks:
    env.reset_task(task)
    env.reset()

    obs = env.reset()
    img = env.render(mode='rgb_array')

    images = []

    for i in range(video_length + 1):
        env.reset()
        print('---')
        images.append(img)
        action = model.predict(obs)
        obs, _, _, _ = env.step(action[0])
        img = env.render(mode='rgb_array')

    imageio.mimsave(
    'renders/reptile/' + str(task['direction']) + '.gif', 
        [np.array(img) for i, img in enumerate(images) if i%2 == 0], 
        fps=29,
    )


env.close()

c:\Users\ssuro\anaconda3\envs\torch\lib\site-packages\gym\core.py:51: DeprecationWarning: WARN: The argument mode in render method is deprecated; use render_mode during environment initialization instead.
See here for more information: https://www.gymlibrary.ml/content/api/
  deprecation(


[ 9.23847159e-02 -6.23452859e-04  9.95723192e-01]
[ 0.07895852 -0.01893551  0.99669805]
[ 0.06983256 -0.04331124  0.99661806]
[ 0.07288756 -0.01527293  0.99722322]
[0.08211264 0.06780702 0.99431369]
[0.10170122 0.1090683  0.98881797]
[0.1343685  0.09365939 0.98649532]
[0.16179594 0.07115766 0.98425538]
[0.17742092 0.04997891 0.98286516]
[0.17212182 0.04904752 0.98385386]
[0.14774328 0.09559826 0.98439468]
[0.11540414 0.19072939 0.97483546]
[0.07842132 0.35904374 0.93002026]
[0.03988514 0.55350619 0.83188946]
[0.00517046 0.69944412 0.71466859]
[-0.0217876   0.80004212  0.59954808]
[-0.03820189  0.86554686  0.49936885]
[-0.04266352  0.91600548  0.3988907 ]
[-0.0362843   0.94911695  0.31282658]
[-0.02670692  0.96839723  0.24797892]
[0.00104292 0.97927036 0.20255489]
[0.05191109 0.98695668 0.15238686]
[0.10284447 0.9932863  0.05296543]
[ 0.13972151  0.98601922 -0.09079643]
[ 0.15448369  0.95441563 -0.25539302]
[ 0.15105184  0.88975632 -0.43071689]
[ 0.13729835  0.79596075 -0.58957242]
[ 0.

KeyboardInterrupt: 